### ISSUE TITLE
[tree][navigator] The tree selection does not stretch horizontally anymore 

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1945]
![selection-does-not-stretch-in-navigator](https://user-images.githubusercontent.com/1405703/40471440-fae3f59c-5f36-11e8-8a7a-b5c20c7daeea.gif)

Also in the `Outline` view. I did not check the others.

Current:
<img width="192" alt="screen shot 2018-05-24 at 09 45 49" src="https://user-images.githubusercontent.com/1405703/40471565-530d344a-5f37-11e8-984b-d0cb1a5e43c0.png">

Expected:
<img width="202" alt="screen shot 2018-05-24 at 09 46 33" src="https://user-images.githubusercontent.com/1405703/40471587-639faf36-5f37-11e8-8815-76976c710ad0.png">

The breaking change: https://github.com/theia-ide/theia/commit/4996f9beefdf33be64236f5dba728ffcf3517e28#diff-83813e5ae443df2f48ba9a887da9a86dR26

**Comment by elaihau** [comment]
@kittaakos mentioned this one when he was reviewing my PR.

To answer the question in his review comments, I found the following:
```css
.theia-TreeNode {
    line-height: var(--theia-private-horizontal-tab-height);
    display: flex;
    align-items: baseline;
    margin-right: 10px;
}
```
I believe that `margin-right` is the cause of this one.
