### ISSUE TITLE
Theia attemps to find 'alive' file starting with double slashes and fails

### ISSUE THREAD

**Issue by vboufleur** [theia-ide/theia#2218]
Hi all!

Currently I'm getting a lot of 404 errors related to Theia not finding the `ROOT_URL//theia` file. I can get the file sucessfully when I manually attempt to get it by `ROOT_URL/theia` (one slash), but Theia is trying `ROOT_URL//theia` (two slashes) and failing.

You guys know what is going on? Where the code that sets the URL for the `alive` functionality is and how to make it use only one slash?

Below is how I'm deploying Theia, in a stack, network is running behind a instance of Docker Flow's proxy:

```
theia:
    image: theiaide/theia
    restart: "on-failure"
    volumes:
      - SENSITIVE_INFO
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=SENSITIVE_INFO
        - com.df.port=3000
```
