### ISSUE TITLE
Theia behind proxy with path /theia

### ISSUE THREAD

**Issue by PierreNowak** [theia-ide/theia#2650]
Hello,

I can't find the way to deploy theia behind a proxy.
If I a configure the proxy to strip the path, I get to /theia but then it asks for /bundle.js and not /theia/bundle.js
Is there a "base url" param so I can set it to "/theia" and then tell my proxy not to strip the path ?

Thanks

**Comment by trowj** [comment]
I've had to work around this problem as well - currently, i'm simply placing a simple nginx container in front of Theia (so instead of Traefik -> Theia, it's Traefik -> Nginx -> Theia). I'm also running in docker entirely so that may affect my options. While I would love to not have to do this, it does work so might provide the needed workaround for now for others.

My simplified docker-compose:
```
services:
  router:
    image: traefik:1.7-alpine

  theia-rewriter:
    image: nginx:1.15-alpine
    labels:
      - "traefik.basic.frontend.rule=PathPrefix:/theia/"

  theia:
    image: theiaide/theia

```
And the related nginx.conf:
```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    tcp_nopush     on;

    keepalive_timeout  65;

    server {
        listen 80;
        location /theia/ {
            rewrite ^/theia(/.*)$ $1 break;
            proxy_pass http://theia:3000/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
}
```
