### ISSUE TITLE
Left margin is added for all buttons

### ISSUE THREAD

**Issue by delislesim** [theia-ide/theia#4430]
I was adding a button to my extension when I came across an undesirable behavior in my opinion. A left margin is added to every button in Theia, not only for _.theia-button_. I think the styling should be left to the extenders. Currently, every button have the same style as _.theia-button_ and you need to override every undesirable properties to make your own button style.

In theia/packages/core/src/browser/style/index.css:
```css
button, .theia-button {
    border: none;
    color: var(--theia-ui-button-font-color);
    background-color: var(--theia-ui-button-color);
    min-width: 65px;
    outline: none;
    cursor: pointer;
    padding-left: 9px;
    padding-right: 9px;
    padding-top: 4px;
    padding-bottom: 4px;
    margin-left: calc(var(--theia-ui-padding)*2);
    border-radius: 1px;
    box-shadow: 0px 1px 5px 0px rgba(0, 0, 0, 0.2), 0px 1px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 1px -2px rgba(0, 0, 0, 0.12);
    transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms,box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;
}

button:hover, .theia-button:hover {
  background-color: var(--theia-ui-button-color-hover);
}
```
