### ISSUE TITLE
Info of parameterHintsWidget overflows

### ISSUE THREAD

**Issue by AlbertXiao1994** [theia-ide/theia#5406]
### Description
![image](https://user-images.githubusercontent.com/23646755/59185608-804d7200-8ba3-11e9-8aef-49ca4ee0c65c.png)

**OS and Theia version:**
Theia v0.7.0

### Suggestion
now:
```css
.monaco-editor .parameter-hints-widget>.wrapper {
  max-width: 440px;
  display: flex;
  flex-direction: column;
 }
```

fix:
```
.monaco-editor .parameter-hints-widget>.wrapper {
  max-width: 440px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
```
