### ISSUE TITLE
[quick-open] fix font-awesome icon alignment

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5726]
**Description**

The `font-awesome` icons present in the quick-open menus are not aligned properly (not centered).

**Steps to Reproduce**

1. run the command `View: Show All Opened Terminals`.
2. notice the alignment of the **+** icon is off.

**Suggested Fix**

The following file and css should be updated:
https://github.com/theia-ide/theia/blob/da653c2692ad65c865ca5ba96b865b270cc916ff/packages/monaco/src/browser/style/index.css#L30-L33

```css
.monaco-quick-open-widget .quick-open-tree .quick-open-entry .quick-open-entry-icon.fa { 
    background-image: none;
    display: flex;
    justify-content: center;
    align-items: center;
    margin-right: 0px; 
} 
```

----

<div align='center'>

<img width="842" alt="Screen Shot 2019-07-16 at 10 50 09 AM" src="https://user-images.githubusercontent.com/40359487/61304654-855f9b80-a7b7-11e9-9a7c-9a22a8198037.png">

</div>
