### ISSUE TITLE
[vscode][webview] support theming-webview-content

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5978]
### Description
webview need impl theming-webview-content
vscode doc
https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content
we can add theme info to body

```html
<body class="vscode-dark">

</body>
```

```css
body.vscode-light {
  color: black;
}

body.vscode-dark {
  color: white;
}

body.vscode-high-contrast {
  color: red;
}
```

- [x] support theme #5981 
- [ ] support CSS variables
```
Webviews can also access VS Code theme colors using CSS variables. 
These variable names are prefixed with vscode and replace the . with -. 
For example editor.foreground becomes var(--vscode-editor-foreground)
```
- [ ] support Theme Color [Reference](https://code.visualstudio.com/api/references/theme-color)
- [ ] support font related variables

### Reproduction Steps

- ext install humao.rest-client
- before add theme class
![image](https://user-images.githubusercontent.com/10203793/63251099-995b5900-c29f-11e9-9bf4-50473c6156e7.png)
- after add theme class
![image](https://user-images.githubusercontent.com/10203793/63251133-ae37ec80-c29f-11e9-80d6-f2e4a0801fbd.png)

**OS and Theia version:**
**Diagnostics:**
